### ISSUE TITLE
 Could you provide me a sample Excel workbook file? I don't know what the 

### ISSUE THREAD

**Issue by mujingfatasy** [haymanjoyce/gantt#1]
Hello, Could you provide me a sample Excel workbook file? I don't know what the workbook format is.

**Comment by haymanjoyce** [comment]
Hi, I haven't touched this project for a while.  "gantt" repo used GUI.  I am getting going with "tool" now which uses CLI.  I think "gantt" GUI does not work at the moment.  Here's a file and screenshot.
[template.xlsx]
(https://github.com/haymanjoyce/gantt/files/12753925/template.xlsx)
![Screenshot 2023-09-28 220201](https://github.com/haymanjoyce/gantt/assets/7354248/673d84b3-eed3-482a-a6c0-2e39734cfb30)
